### ISSUE TITLE
Don't .catch(reject)

### ISSUE THREAD

**Issue by mgree** [rwoll/submission#43]
Apparently this is redundant.

**Comment by mgree** [comment]
It is, in fact, not redundant. If we remove the `.catch(reject)` and cause an exception, we get:

```
Unhandled rejection Error: Not authorized to enroll.
    at .<anonymous> (/Users/mgree/submission/src/server/dbwrap.js:572:15)
    at tryCatcher (/Users/mgree/submission/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mgree/submission/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/mgree/submission/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/mgree/submission/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/mgree/submission/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/mgree/submission/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/mgree/submission/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mgree/submission/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

So in fact this is the correct behavior. Why it's not the _default_ behavior, I have no idea.

**Comment by rwoll** [comment]
@mgree It depends where you are, I believe. If you are inside another promise/callback then it is not redundant, but if you throw from the top-level of the promise you created then it will automatically trigger a reject. 

i.e. 

```javascript
new Promise(function(resolve, reject) {
    throw new Error('This will auto call reject.');
});
```

```javascript
new Promise(function(resolve, reject) {
    models
        .User
        .findById(1)
        .then(function(user) {
            throw new Error('This will not call the reject :(  ')
        });
});
```

Regardless, I think it's fine to call it in either case since it makes it clearer.
